#Leaving & Entries
- alias: 'Home (Alvaro)'
  trigger:
    platform: state
    entity_id: device_tracker.alvaro_alvaro
    from: 'not_home'
    to: 'home'
  action:
    - service: group.set_visibility
      entity_id: group.MorningInfo
      data:
        visible: True
    - service: notify.homeassistant
      data:
        title: "Alvaro is home"
        message: "Alvaro has just arrived home"
 
- alias: 'Leaving (Alvaro)'
  trigger:
    platform: state
    entity_id: device_tracker.alvaro_alvaro
    from: 'home'
    to: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: group.set_visibility
      entity_id: group.MorningInfo
      data:
        visible: False
    - service: notify.homeassistant
      data:
        title: "Alvaro just left home"
        message: "Alvaro has just left home"
- alias: 'Home (Rodrigo)'
  trigger:
    platform: state
    entity_id: device_tracker.rodrigo_rodrigo
    from: 'not_home'
    to: 'home'
  action:
    - service: notify.homeassistant
      data:
        title: "Rodrigo is home"
        message: "Rodrigo has just arrived home"
- alias: 'Leaving (Rodrigo)'
  trigger:
    platform: state
    entity_id: device_tracker.rodrigo_rodrigo
    from: 'home'
    to: 'not_home'
  action:
    - service: notify.homeassistant
      data:
        title: "Rodrigo just left home"
        message: "Rodrigo has just left home"
        
        

#Media
- alias: 'Media Refresh (Outside)'
  trigger:
    platform: state
    entity_id: media_player.outside
  action:
    service: input_slider.select_value
    data_template:
      entity_id: media_player.outside
      value: '{{ states.media_player.outside.attributes.volume_level }}'
- alias: 'Volume Outside'
  trigger: 
    platform: state
    entity_id: input_slider.volume_outside
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.outside
      volume_level: '{{ trigger.to_state.state | float }}'
- alias: 'Media Refresh (Inside)'
  trigger:
    platform: state
    entity_id: media_player.alvaros
  action:
    service: input_slider.select_value
    data_template:
      entity_id: media_player.alvaros
      value: '{{ states.media_player.alvaros.attributes.volume_level }}'
- alias: 'Volume Inside'
  trigger: 
    platform: state
    entity_id: input_slider.volume_alvaros
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.alvaros
      volume_level: '{{ trigger.to_state.state | float }}'
      

#Night turn off
- alias: 'Turn off everything'
  trigger:
    platform: time
    after: '02:30:00'
  condition:
    condition: state
    entity_id: device_tracker.alvaro_alvaro
    state: 'home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: media_player.media_pause
      entity_id: media_player.alvaros
      
      

#Alarm
- alias: 'Alarm Clock'
  trigger:
    platform: time
    minutes: '/5'
  condition: 
    condition: and
    conditions:
      - condition: template
        value_template: '{{ now().strftime("%H:%M") == states.input_select.alarm_clock.state }}'
      - condition: state
        entity_id: media_player.alvaros
        state: 'paused'
      - condition: state
        entity_id: input_boolean.alarm_clock
        state: "on"
  action:
    - service: media_player.select_source
      data:
        entity_id: media_player.alvaros
        source: 'Hunting for Witches'
    - service: media_player.volume_set
      data:
        entity_id: media_player.alvaros
        volume_level: .4
- alias: 'Stop Alarm'
  trigger:
    platform: state
    entity_id: input_boolean.alarm_clock
    to: 'off'
  action:
    service: media_player.media_pause
    data:
      entity_id: media_player.alvaros



#Script Stop
- alias: 'Stop Music Night'
  trigger:
    platform: state
    entity_id: script.night_music
    to: "off"
  action:
    service: media_player.media_pause
    data:
      entity_id: media_player.alvaros


