homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 25.683539
  longitude: -80.166588
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  
  customize:
    light.back_room_light:
      friendly_name: Back Room Light
  

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr
  
# Text to speech
tts:
  platform: google

#Media
media_player:
  - platform: sonos
    hosts: 10.0.0.31

# Cameras Security
camera:
  - platform: foscam
    ip: 10.0.0.177
    username: cam1    
    password: !secret cam1_pass
    port: 88

#Shell commands
shell_command: !include shell_command.yaml

#MQTT
mqtt:
  broker: m13.cloudmqtt.com
  port: 10944
  client_id: homeassistant
  keepalive: 60
  username: !secret broker_user
  password: !secret broker_pass
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true
#Trackin
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
zone:
  name: Home
  latitude: 25.683539
  longitude: -80.166588
  radius: 400
  icon: mdi:home

#Customization
group:
  default_view:
    view: yes
    entities:
      - device_tracker.phone_phone
      - light.back_room_light
  Surveillance:
    view: yes
    entities:
      - camera.foscam_camera
  Media:
    view: yes
    entities:
      - media_player.alvaros

#Wink
wink:
  access_token: !secret wink_access_token

#Automations
automation:
- alias: 'Turn off Room lights when I leave'
  trigger:
    platform: state
    entity_id: device_tracker.phone_phone
    state: 'not_home'
  action:
    service: light.turn_off
    entity_id: light.back_room_light
    
- alias: 'Turn off lights at night if im home'
  trigger:
    platform: time
    after: '02:00:00'
  condition:
    condition: state
    entity_id: device_tracker.phone_phone
    state: 'home'
  action:
    service: light.turn_off
    entity_id: light.back_room_light
    
#Scripts
script:
  update_config:
    sequence:
      - service: shell_command.get_latest_config
      - service: homeassistant.restart