homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.370126
  longitude: -71.078153
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2.7
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customize.yaml


# Enables the frontend
frontend:

http:
  ssl_certificate: /home/homeassistant/.homeassistant/fullchain1.pem
  ssl_key: /home/homeassistant/.homeassistant/privkey1.pem
  base_url: hass-ac.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discoery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#iOs
ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

# Weather Prediction
sensor:
  - platform: yr

  - platform: google_travel_time
    api_key: AIzaSyC_qJ81D5L7d6k5MPVWB3YGNlImBzscED4
    origin: 1 Leighton St Cambridge
    destination: 675 Commonwealth St Brookline
    name: 'ETA Home-BU'

  - platform: google_travel_time
    api_key: AIzaSyC_qJ81D5L7d6k5MPVWB3YGNlImBzscED4
    origin: 1 Leighton St Cambridge
    destination: 415 South St, Waltham, MA 02453
    name: 'ETA Home-Brandeis'

  - platform: uber
    server_token: keSesSEqKCxZndb-IVOfJWy_rWfiq5fBq4-zXm-g
    start_latitude: 42.370113
    start_longitude: -71.073655
    end_latitude: 42.350504
    end_longitude: -71.105404
    product_ids:
      - '2d1d002b-d4d0-4411-98e1-673b244878b2'

  - platform: uber
    server_token: keSesSEqKCxZndb-IVOfJWy_rWfiq5fBq4-zXm-g
    start_latitude: 42.370113
    start_longitude: -71.073655
    end_latitude: 42.365045
    end_longitude: -71.258225
    product_ids:
      - '2d1d002b-d4d0-4411-98e1-673b244878b2'
# Text to speech
tts:
  platform: google

#Automations
#automation: !include automation.yaml

#Scripts
script: !include script.yaml

#Inputs
#input_select: !include selects.yaml

#Booleans
#input_boolean: !include booleans.yaml

#Sliders
#input_slider: !include sliders.yaml

#Groups
group: !include groups.yaml

#Notifications
notify:
  - platform: ios
    name: ios_alvaro
    target: f729c78b-c577-3876-b34f-1fcffc8fb067

#Shell commands
shell_command: !include shell_command.yaml

#MQTT
#mqtt:
  #broker: m13.cloudmqtt.com
  #port: 10944
  #client_id: homeassistant
  #keepalive: 60
  #username: !secret broker_user
  #password: !secret broker_pass
  #birth_message:
  #  topic: 'hass/status'
  #  payload: 'online'
  #  qos: 1
  #  retain: true
  #will_message:
  #  topic: 'hass/status'
   # payload: 'offline'
   # qos: 1
   # retain: true


#Wink
#wink:
  #access_token: !secret wink_access_token

#Alexa
#alexa:
  #intents: !include_dir_merge_named alexa
