homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 25.683539
  longitude: -80.166588
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  
  customize:
    light.back_room_light:
      friendly_name: Back Room Light
    sensor.eta_homeschool:
      friendly_name: Home to School
      icon: mdi:timer-sand
    group.MorningInfo:
      friendly_name: Driving
      order: '2'
    group.alvaro_lights:
      friendly_name: Lights
      order: '1'
    group.alarm_clock:
      friendly_name: Alarm Clock
      control: hidden
    group.all_scripts:
      friendly_name: Commands
      hidden: false
      control: hidden
    group.volume_control:
      friendly_name: Media Control
    script.night_music:
      icon: mdi:music-circle
    script.say:
      hidden: true
    device_tracker.beacon_varocar:
      icon: mdi:car
      friendly_name: C63 AMG
    device_tracker.alvaro_alvaro:
      entity_picture: https://mybluerobot.com/wp-content/plugins/svg-avatars-generator/data/temp-avatars/svgA21230366034433246.png
    device_tracker.rodrigo_rodrigo:
      entity_picture: https://mybluerobot.com/wp-content/plugins/svg-avatars-generator/data/temp-avatars/svgA026911773076625956.png
      
     
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  
  - platform: google_travel_time
    api_key: AIzaSyCzCLAODj0XpjXyT8tKBr2Q9_EvVOSukJI
    origin: 1040 Mariner Dr Key Biscayne
    destination: 6575 N Kendall Dr Pinecrest
    name: 'ETA Home-School'
# Text to speech
tts:
  platform: google

#Automations
automation: !include automation.yaml

#Scripts
script: !include script.yaml

#Inputs
input_select: !include selects.yaml

#Booleans
input_boolean: !include booleans.yaml

#Sliders
input_slider: !include sliders.yaml

#Notifications
notify:
  - name: HomeAssistant
    platform: pushbullet
    api_key: o.BztWEwiqEoUY1kIjpN3gV5p3P4JnJBZL

#Media
media_player:
  - platform: sonos
    hosts: 
      - 10.0.0.31
      - 10.0.0.208

# Cameras Security
camera:
  - platform: foscam
    ip: 10.0.0.177
    username: cam1    
    password: !secret cam1_pass
    port: 88

#Shell commands
shell_command: !include shell_command.yaml

#MQTT
mqtt:
  broker: m13.cloudmqtt.com
  port: 10944
  client_id: homeassistant
  keepalive: 60
  username: !secret broker_user
  password: !secret broker_pass
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true
#Trackin
device_tracker:
  - platform: owntracks
    waypoints: True

zone:
  - name: Home
    latitude: 25.683539
    longitude: -80.166588
    radius: 100
    icon: mdi:home
  - name: "G Prep"
    latitude: 25.689507
    longitude: -80.299706
    radius: 400
    icon: mdi:school
  - name: "Miller"
    latitude: 25.716813
    longitude: -80.325366
    radius: 200
    icon: mdi:school
  - name: Ashlee
    latitude: 25.719046
    longitude: -80.307822
    radius: 150
    icon: mdi:home
    
#Panels
panel_iframe:
  dominos:
    title: 'Dominos'
    url: "https://www.dominos.com"
    
#Customization
group:
  default_view:
    view: yes
    entities:
      - device_tracker.alvaro_alvaro
      - device_tracker.rodrigo_rodrigo
      - group.alvaro_lights
      - group.all_scripts
      - group.MorningInfo
      - group.alarm_clock
      - group.cars
      - group.volume_control
  Surveillance:
    view: yes
    entities:
      - camera.foscam_camera
  Media:
    view: yes
    entities:
      - media_player.alvaros
      - media_player.outside
  MorningInfo:
    entities:
      - sensor.eta_homeschool
  alvaro_lights:
    icon: mdi:light
    entities:
      light.back_room_light
  cars:
    entities:
      - device_tracker.beacon_varocar
  alarm_clock:
    icon: mdi:alarm
    entities:
      - input_select.alarm_clock
      - input_boolean.alarm_clock
      - input_boolean.lightalarmclock
  volume_control:
    icon: mdi:music-note-eighth
    entities:
      - input_slider.volume_outside
      - input_slider.volume_alvaros
 
#Wink
wink:
  access_token: !secret wink_access_token
